[[hooks]]
stage = "pre_build"
command = "bash"
command_arguments = ["-c", "npm run build:css"]

[hooks.windows]
stage = "pre_build"
command = "cmd"
command_arguments = ["/c", "npm run build:css"]

[[hooks]]
stage = "pre_build"
command = "nu"
command_arguments = ["scripts/nu/compile_assets.nu", "scripts/nu", "assets", "styles", "target"]